### ISSUE TITLE
defaultOpenLevel sidebar prop not working

### ISSUE THREAD

**Issue by ZYJLiu** [fuma-nama/fumadocs#1085]
### To Reproduce

The sidebar tab remains closed by even though `defaultOpenLevel: 1`

1. Create new fumadocs project using `npm create fumadocs-app`

2. Create `content/docs/test/test.mdx` to display "test.mdx" under a "test" tab in sidebar

<img src="https://github.com/user-attachments/assets/feacfe8f-c181-4dc3-9977-af0b81efc395" width="300" alt="CleanShot 2024-11-20 at 14 49 30@2x" />

3. Update `app/docs/layout.tsx` with `sidebar={{ defaultOpenLevel: 1 }}`

```ts
import { DocsLayout } from "fumadocs-ui/layouts/docs";
import type { ReactNode } from "react";
import { baseOptions } from "@/app/layout.config";
import { source } from "@/lib/source";

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <DocsLayout
      tree={source.pageTree}
      {...baseOptions}
      sidebar={{ defaultOpenLevel: 1 }}
    >
      {children}
    </DocsLayout>
  );
}
```

### Current vs. Expected behavior

Currently, folders in sidebar remain closed when using `defaultOpenLevel` prop.

The expected behavior is that they open to the specified level.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020
  Available memory (MB): 32768
  Available CPU cores: 12
Binaries:
  Node: 20.18.0
  npm: 10.8.2
  Yarn: 1.22.1
  pnpm: 9.1.2
Relevant Packages:
  next: 15.0.3 // Latest available version is detected (15.0.3).
  eslint-config-next: 15.0.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

UI

**Comment by fuma-nama** [comment]
Oh yes the initial sidebar level was mistakenly increased to 1, should be fixed now

**Comment by ZYJLiu** [comment]
`defaultOpenLevel` still doesn't seem to work, using `14.5.2`

**Comment by fuma-nama** [comment]
The fix is on the latest version, have you updated?

**Comment by ZYJLiu** [comment]
working now with 14.5.4, ty!
