### ISSUE TITLE
MDX Hot-Reload breaks dev

### ISSUE THREAD

**Issue by brian-lou** [fuma-nama/fumadocs#1878]
### To Reproduce

1. Run `npm run dev`
2. Create a new blank .mdx file

### Current vs. Expected behavior

When I'm working on docs with `npm run dev` running on the side, if I try to create a new docs page by creating a new .mdx file, the hot-reload dev server immediately tries parsing this blank mdx file and errors out:

```
[Error: invalid frontmatter in /Users/brian/gt/gt-libraries/docs/content/docs/en/react/introduction.mdx::
  title: Required]
 ⨯ unhandledRejection: [Error: invalid frontmatter in /Users/brian/gt/gt-libraries/docs/content/docs/en/react/introduction.mdx::
  title: Required]
 ⨯ unhandledRejection:  [Error: invalid frontmatter in /Users/brian/gt/gt-libraries/docs/content/docs/en/react/introduction.mdx::
  title: Required]
```

This causes the dev server to hang indefinitely while attempting to loading any page, and requires a complete SIGKILL & server restart.
Ideally, the MDX parser should not be causing this error, and creating a new docs page should not necessitate a complete server restart.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.5.0: Thu Apr 10 20:22:55 PDT 2025; root:xnu-11417.120.96.501.2~2/RELEASE_ARM64_T6020
  Available memory (MB): 32768
  Available CPU cores: 12
Binaries:
  Node: 23.6.0
  npm: 11.3.0
  Yarn: 1.22.22
  pnpm: 10.9.0
Relevant Packages:
  next: 15.2.3 // There is a newer version (15.3.2) available, upgrade recommended! 
  eslint-config-next: 15.2.1
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.8.2
Next.js Config:
  output: N/A
 ⚠ There is a newer version (15.3.2) available, upgrade recommended! 
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

Core, Content Sources (e.g. Fumadocs MDX, Content Collections)

**Comment by fuma-nama** [comment]
This should be fixed on the new version of Fumadocs MDX already, make sure to update and check again

**Comment by brian-lou** [comment]
Requesting to reopen this issue: On the latest version of fumadocs-mdx, this issue still exists:

```
    "fumadocs-core": "^15.3.4",
    "fumadocs-mdx": "^11.6.5",
    "fumadocs-typescript": "^4.0.5",
    "fumadocs-ui": "^15.3.4",
```

```
 ✓ Compiled in 418ms (6004 modules)
[Error: invalid frontmatter in /Users/brian/gt/gt-libraries/docs/content/docs/en/react/guides/migrations.mdx] {
  issues: [Array]
}
 ⨯ unhandledRejection: [Error: invalid frontmatter in /Users/brian/gt/gt-libraries/docs/content/docs/en/react/guides/migrations.mdx] {
  issues: [Array]
}
 ⨯ unhandledRejection:  [Error: invalid frontmatter in /Users/brian/gt/gt-libraries/docs/content/docs/en/react/guides/migrations.mdx] {
  issues: [Array]
}```

**Comment by fuma-nama** [comment]
Cannot reproduce, the dev server is still running

<img width="844" alt="Image" src="https://github.com/user-attachments/assets/5cfb87f3-ba1f-44fe-b8e4-f07cd8d146a2" />

**Comment by fuma-nama** [comment]
Wait, I tested it again on Webpack, turns out it's because Webpack handles loader error differently. The next version of Fumadocs MDX will improve compatibility with Webpack.
