### ISSUE TITLE
The request for integer arrays on the body are sent as strings and not as integers

### ISSUE THREAD

**Issue by GerardPolloRebozado** [fuma-nama/fumadocs#2586]
### To Reproduce

Generate a documentation page that has an open api schema where the request body contains an array of integers

### Current vs. Expected behavior

generated curl request:
```bash
curl -X POST "http://localhost:8080/api" \
  -H "X-Api-Key: " \
  -H "Content-Type: application/json" \
  -d '{
    "idx": [
      "1"
    ]
  }'
```
but it should be:
```bash
curl -X POST "http://localhost:8080/api" \
  -H "X-Api-Key: " \
  -H "Content-Type: application/json" \
  -d '{
    "idx": [
      1
    ]
  }'
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 25.0.0: Wed Sep 17 21:42:08 PDT 2025; root:xnu-12377.1.9~141/RELEASE_ARM64_T8132
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 22.19.0
  npm: 10.9.3
  Yarn: N/A
  pnpm: 10.17.1
Relevant Packages:
  next: 16.0.1 // Latest available version is detected (16.0.1).
  eslint-config-next: N/A
  react: 19.2.0
  react-dom: 19.2.0
  typescript: 5.8.3
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Integrations (e.g OpenAPI, Typescript DocsGen)

### Additional context

I tested with version 9.7.0 and 10.0.0

**Comment by GerardPolloRebozado** [comment]
May be due to this [line](https://github.com/fuma-nama/fumadocs/blob/c2950bbc1f48ab95e5277a0371af316690f046c3/packages/openapi/src/requests/generators/curl.ts#L30)

**Comment by fuma-nama** [comment]
sorry for late, should be fixed now. Make sure to upgrade :)

**Comment by GerardPolloRebozado** [comment]
Hi, im still having the same error, I have upgraded to version 10.0.2

**Comment by fuma-nama** [comment]
the newer patch should works (10.0.3)

**Comment by GerardPolloRebozado** [comment]
Now it's working thank you very much
